2020/11/13 11:26:21 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.29.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.2:9000", host: "localhost"
2021/02/24 17:05:38 [error] 33#33: *21 FastCGI sent in stderr: "PHP message: 2021-02-24T17:05:38+00:00 [critical] Uncaught Exception: Unrecognized option "base_uri" under "framework.http_client". Available options are "default_options", "enabled", "max_host_connections", "mock_response_factory", "scoped_clients"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost"
2021/02/24 17:06:01 [error] 33#33: *21 FastCGI sent in stderr: "PHP message: 2021-02-24T17:06:01+00:00 [critical] Uncaught Exception: Unrecognized option "base_uri" under "framework.http_client.default_options". Available options are "bindto", "cafile", "capath", "ciphers", "headers", "http_version", "local_cert", "local_pk", "max_duration", "max_redirects", "no_proxy", "passphrase", "peer_fingerprint", "proxy", "resolve", "retry_failed", "timeout", "verify_host", "verify_peer"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost"
2021/02/24 17:21:17 [error] 33#33: *43 FastCGI sent in stderr: "PHP message: 2021-02-24T17:21:17+00:00 [critical] Uncaught Exception: Invalid service "twig.extension.intl": class "Twig_Extensions_Extension_Intl" does not exist" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost"
2021/02/24 17:52:15 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:52:17 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:52:18 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:52:18 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:52:46 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:52:51 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:53:01 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:53:01 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost", referrer: "http://localhost/euro-millions/results"
2021/02/24 17:53:07 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /euro-millions/results HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost"
2021/02/24 17:53:07 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost", referrer: "http://localhost/euro-millions/results"
